---
title: "Sing of Old Djurgården"
date: "2009-11-05"
categories: [personal]
---

Monday morning conversations with my neighbour Niklas over breakfast have been downcast these past few weeks. 'How did Djurgården get on this weekend?', I'll ask tentatively, over the ever-gurgling kitchen coffee-machine. 'Not good. We lost again.' comes the familiar reply, as I stir my tea. 'How about Liverpool?'. 'Ah, don't ask.'

Finding a Stockholm football team to follow has been a task I've put off since my move to Sweden, with plenty else to keep me occupied. Hammarby were the team I'd considered beforehand, but Djurgården turned out to be the local team when I found a place to live. 'The Blue Stripes' play at the beautiful old Olympic stadium, built for the 1912 summer games. It sits between my new home in the north of the city and the campus of Kungliga Tekniska Högskolan where I study, so I pass it on my daily walk.

I often slow down to admire the beautiful brickwork, the clock tower with its battlements and the old telephone boxes outside. You can even see the pitch from the pavement on Valhallav&auml;gen, through the main arch of the structure. And it's close enough to hear the cheers and boos on match days, as a weekly reminder for me to investigate. This season, apparently, there's been few cheers. At the end of a decade of success for Djurgården --- winning Allsvenskan in 2002, 2003 and 2005, along with a bunch of domestic cups --- this season has been awful. Not only has their poor form driven them down into the relegation zone, but they've had to watch as bitter Stockholm rivals AIK have enjoyed a strong campaign at the top.

Seventeen losses seemed to have sealed Djurgården's fate, but a late turn of form and a couple of wins have brought some hope. A vital 2-1 win over the other team facing relegation, Örgryte, was backed up with a surprise 0-2 win at Helsingborg. The match will be remembered as Henrik Larsson's professional bow, but the importance of the result for the future of Djurgården could be huge. Örgryte have slipped below them into the automatic relegation spot, two points behind with just one game to go.

Still, Örgryte only have to beat tenth-placed Gefle in their final game, their team probably planning their skiing holidays; Djurgården's final hurdle is a tough match against fourth-placed Kalmar, who have a Europa League spot to fight for, and against whom they've lost their last three home games. There is still a tough job to do.

Meanwhile, those rivals I mentioned, AIK, sit on top of the league, one point above Göteborg. Remarkably, the fixture list has drawn the old clubs against each other in the final game, with Göteborg holding home advantage. The newspapers, Aftonbladet and Dagens Nyheter, are calling it the Gold Medal Match. This is the kind of excitement I need to distract me from what looks to be a season already over on Merseyside. I jump at Niklas' offer to grab me a ticket for Djurgården's final match.

So this Sunday afternoon in November, I meet Niklas and a couple of his friends, and our neighbour Hamza. 'Aren't you worried about hooliganism, bringing a Turkish and an English to your nice Swedish football?', he teases. The match is a sellout: all 13,000 tickets. The news from Gothenburg is that AIK fans are already causing trouble, smashing every window on the SJ train that brought them west. I've been on one of those fine old locomotives --- I'm building a healthy dislike of AIK already.

Arriving at the stadium, we find our space on the wooden benches. The stands are low, though the running track keeps us a little distant from the action. The club anthem 'Sing of Old Djurgården' comes over the speakers and gets a loud recital, which I am actually able to join in as Hamza has dutifully written down the words after finding them on the internet. I'm mostly chortling through it as he surprises me with these carefully copied notes, and I have no idea what I'm singing about, but it is an enjoyable and rousing tune nonetheless.

Kick off! Djurgården start brightly. The full backs get forward, overlapping and flinging some decent crosses in, though the Kalmar keeper has little trouble plucking them out of the air. Though the home team are bossing possession, the importance of the game is clearly causing some tension with a few wayward touches in midfield.

Relief comes after 27 minutes. A Djurgården corner is headed clear of the box, only for midfielder Patrick Haginge to fire it back goal wards with a sweet half volley low into the bottom right corner of the net. Celebration and hugs all round , on the pitch and in the stands.


Soon after the goal, a quiet cheer spreads around the ground suggesting good news elsewhere. Örgryte are losing at Gefle. And another, much louder, cheer. Göteborg are 1-0 up against AIK. Niklas confirms my suspicion, 'AIK losing is probably as important to us as Djurgården winning.'
Half time arrives, and the crowds descend through brick arches to queue for warm Kanelbullar and more coffee, as we hop around to defrost toes. The faces around us are happy --- all the important results are going the right way.

Settling back in for the second half, a little tension seeps back in to the crowd. Örgryte have equalised in their match, and Kalmar have woken up a bit. A few high balls leave the centre-halves looking uncomfortable, and only a well placed shin blocks a dangerous run into the box from the left wing. Mercifully, on 56 minutes, Djurgården pick up a second goal. Again, it's from a corner. This time an attacker gets his head to the ball first on the back post, though without sufficient power to score. A messy goalmouth scramble ends with a decisive touch from veteran defender Markus Johannesson --- a nice way to end his final season at the club.

Relief in Stockholm is tempered by bad news from Gothenburg. AIK have equalised, putting them back on top of the pile. Göteborg need a win to take the title.

I try, through the match, to pick up terrace songs. The tunes are easy enough, as even these seem to be a part of the globalised game. We sing 'Na, na, na, ..., Djurgården' to the tune of Hey Jude, and an amusing 'Steve Galloways Jarnkaminerna' to the 'Barmy Army' tune --- Steve Galloway being their English assistant manager (he played at St. Mirren and Crystal Palace, apparently) and 'Jarnkaminerna' ('The Iron Stoves') the fan club. If I close my eyes, I could easily be at Rochdale or York City, but for the lack of dietary advice directed at the away goalkeeper. I find the chants a little disappointing in their politeness, to be honest. One promisingly aggressive call-and-response from the left stand to the right turns out to be 'Let's move forward!', 'But keep the defence tight!', 'Let's move forward!', 'But keep the defence tight!'. That's just practical. Can't we at least discuss their striker's parentage briefly? After the second goal, Kalmar lose some of their fight and the game goes a bit quiet. Apart from trying to follow songs, the best entertainment arrives when the Djurgården goalkeeper slices four goal kicks in a row high into the left stand. Only one goes further than the half way line. Four in a row! I hope he has somewhere to practice over the winter when the snow sets deep.


The relief of getting their win is clear in the players' celebrations at the final whistle, lapping the pitch to thank their support. Still waiting for results around the country, the disappointing news arrives: AIK have scored a late winner to confirm they'll be bringing the Allsvenskan trophy back to parade around Stockholm. And there'll likely be more riots in Gothenburg for Jens Lekman to sing about.


So then, Göteborg didn't manage to stop AIK but Djurgården did what they needed to do. Most importantly, I care about a club here. I'm looking forward to next season already.