---
title: "Book Notes, 2022"
date: "2022-12-31"
categories: [reading]
---

1. _Manchester: Mapping the City_ by Terry Wyke, Brian Robson and Martin Dodge --- Tells
the history of Manchester through cartography, which makes for a compelling and visually
interesting way of storytelling. Especially if you love maps, and I do.

2. _Project Hail Mary_ by Andy Weir --- Enjoyable for me in the same way _The Martian_
was as a light, problem-solving epic with care taken over scientific realism. This ones
heads a bit further into the future and into sci-fi.

3. _Pole to Pole_ by Michael Palin --- Palin heads from north to south along the 30°E
line of longitude as best he can on icebreaking ships and trains.

4. _Built_ by Roma Agrawal --- A run through the world of civil engineering. Agrawal is
a structural engineer and describes the history and science of bridges, tunnels, sewers
and skyscrapers like the Shard, which she helped design.

5. _The Spy and the Traitor_ by Ben Macintyre --- A riveting nonfiction tale of Cold War
spycraft focused on Oleg Gordievsky, a KGB officer who became a double agent for British
intelligence. The narrative digs into Gordievsky's disillusionment with the Soviet
regime, his recruitment as a spy for MI6 and the dangerous operation to
smuggle him across the border to Finland when his betrayal was uncovered.

6. _Metropolis_ by Ben Wilson --- This book chronicles the evolution of cities over
5,000 years from ancient Uruk, Athens, Alexandria and Rome through 12th century Baghdad,
18th century London, 19th century Manchester, and 20th Century New York and Tokyo.
Wilson covers their importance to the progress of civilisation, serving as hubs of
culture, trade, innovation and political power.

7. _The Honourable Schoolboy_ by John le Carré --- The second book in the Karla trilogy
after _Tinker Tailor_. Smiley wants to restore the reputation of the Circus. Jerry
Westerby, journalist turned spy, is sent to Southeast Asia to uncover a money laundering
operation linked to Karla. Espionage, political intrigue and a study on identity,
loyalty and duty. I enjoyed the scene setting across Hong Kong, Laos, Vietnam and
Cambodia in this one.

8. _The Fifth Elephant_ by Terry Pratchett --- Vimes is sent across the disc as an
ambassador to Überwald, where the coronation of the new Dwarf King is about
to take place if the missing Scone of Stone can be found.

9. _The Two Penny Bar_ by George Simonen --- Maigret is back in Paris to investigate a
   couple of murders at a riverside bar with wealthy, boozy clientele.

10. _The Black Echo_ by Michael Connelly --- the first of the Hieronymus Bosch LA
detective novels.

11. _Northerners_ by Brian Groom --- A history of Nothern England and its people 
including the Roman emperors who ruled from York, Anglo-Saxon Northumbria, Viking
invasion, the Industrial Revolution and recent decades. I would argue against
the case that there is any overarching Northern English identity but an
interesting and informative read nonetheless.

12. _Night Watch_ by Terry Pratchett --- There's the fun of time travel paradoxes in
this one as Vimes is sent back to his past to help his younger self while dealing with a
psychopathic killer.

13. _Spies in Canaan_ by David Park --- Took a while to build for a short book I thought
but the imagery both in Saigon and the US was great. A concise, introspective allegory
of guilt and atonement.

14. _Time on Rock_ by Anna Fleming --- I loved this both for how good Fleming is at
describing the feeling of climbing on rock and of the landscapes, and with
nostalgia because these are scenes I know well from my own days learning to climb in the
Lakes, north Wales, the Cairngorms and the Peak District. Made me want to get out in the
mountains immediately.

15. _Rogues_ by Patrick Radden Keefe --- A collection of twelve of Keefe's articles from
_The New Yorker_ on arms dealers, druglords, fraudsters and more. All deeply engaging.

16. _The Colour of Magic_ by Terry Pratchett --- I thought at this point I'd start from
the beginning, partly because I wanted to start collecting the newish Gollancz
clothbound editions. 

17. _Smiley's People_ by John le Carré --- The final installment in the Karla trilogy.
Smiley is retired but heads back to the Circus for one last mission after 'The
Estonian', a former agent, tries to contact him and then turns up dead. It leads back to
Karla of course and we land on the showdown between the two battlescarred grandmasters
of the spy game.
