---
title: "Book Notes, 2020"
date: "2020-12-31"
categories: [reading]
---

1. [_The Big Sleep_][bs-big-sleep] by Raymond Chandler ★ --- The first Philip
   Marlowe book. I have to write 'hardboiled' here.
  
2. [_I, Robot_][bs-i-robot] by Peter Crouch --- Bought for the title.

3. [_Stories of the Law and How It's Broken_][bs-secret-barrister] by The Secret
   Barrister --- In 2018 I spent two weeks as a juror on a trial. Welcoming us,
   the judge said something to the effect of 'this system isn't perfect but it's
   the best we've found.' The anonymous author here describes the many ways the
   neglected and underfunded criminal justice system in England is far from
   perfect.

4. [_Green River, Running Red_][bs-green-river] by Ann Rule --- True crime story
   of the Green River Killer in Seattle in the 80s and 90s.

5. [_Life Undercover_][bs-undercover] by Amaryllis Fox --- A memoir of a fairly
    exceptional early life and years as a CIA operative.

6. [_A Tale of Two Cities_][bs-two-cities] by Charles Dickens --- Think about
   what it would have been like to read the tale the way it was first published
   in weekly installments, like an HBO series pulling its story arcs together
   for an epic finale. Dickens pulling subscribers into his new publishing
   startup. The least Dickensian of his novels for its shift of weight from
   character to plot.

   'Recalled to life.' For a book with among the most famous first and last
   lines of any written, the note handed to the banker on the Dover mail coach
   tells us most of what it's about. Hope and resurrection form a thin line
   between humanity and terror.
     
7. [_The Snow Leopard Project_][bs-snow-leopard] by Alex Dehgan --- A report
   from the ground on wildlife conservation in the warzones of Afghanistan.
  
8. [_Russian History_][bs-russian-hist] by Geoffrey Hosking --- It's interesting
   to consider how much the political history of Russia is affected by its
   geography: a uniquely vast place much of which has hostile climate, diverse
   in people. This is a short introduction.
  
9. [_A Line in the Sand_][bs-sand] by James Barr --- A stroke of pen on a map
   with long-lasting effect, in 1916 Sykes and Picot partitioned the territories
   of the Ottoman Empire in the Middle East between the empires of Britain and
   France. Barr sources declassified archives to tell the inglorious colonialist
   history through the decades that followed.

10. [_The Idea of the Brain_][bs-brain] by Matthew Cobb ★
    --- An enlightening history of our understanding of probably the most
    complex and inscrutible object we know of. The book combines a chronicle of
    ideas since Aristotle and a tour of the current state of neuroscience.

    I suppose my prior conception of the brain would be a naturally evolved
    computer that allows organisms to control physical functions, learn and
    respond to the environment. Cobb makes a clear argument that the computer is
    just the latest in a line of metaphors based on the technology of the day:
    mechanical clockwork, hydraulic automaton, telephone exchange and on. The
    brain _computes_ but it is not much like a digital computer. It is
    electrochemical and analogue. Localising functions to particular parts of
    the brain is mostly not possible.

    I tend to credit physics for pushing much of 20th century progress in
    computing. That notion is countered here in the influence of neuroscience
    from the 40s, with Alan Turing's test and John von Neumann's interest in
    how neural circuits might encode information, to the 80s, with the work of
    Geoffrey Hinton _et al._ on backpropagation and the Perceptron.[^crick] Thus
    especially recommended if you are interested in machine learning.

11. [_Feet of Clay_][bs-clay] by Terry Pratchett ↻ ---
    At 13, my English teacher noticed I wasn’t reading any fiction. Given time
    to read in school I’d head for a world atlas. At home I read a lot but
    mostly bible study.[^jw] Mrs Clarke clearly had a good eye for what might
    catch my interest and wrote 'Terry Pratchett' in my schoolbook with homework
    to find a novel of his in the library and report back on it.

    The one I found was _Moving Pictures_ and I’d never read anything like it. I
    went back to the library for the first Discworld book, then the second. My
    mum worked in a WH Smith shop and told me there was going to be a new book
    in the series called _Feet of Clay_. This was exciting, I had not considered
    there would be new ones. She ordered it for me and then through _Hogfather_,
    _Jingo_, _The Last Continent_, _Carpe Jugulum_ and _The Fifth Elephant_ I
    bought each paperback when it came out.

    > And, while it was regarded as pretty good evidence of criminality to be
    > living in a slum, for some reason owning a whole street of them merely got
    > you invited to the very best social occasions.

12. [_The Warmth of Other Suns_][bs-warmth] by Isabel Wilkerson ★ --- A narrative history of the Great Migration of African
    Americans from the Southern US to Northern and West Coast cities in the
    twentieth century, pushed by Jim Crow oppression and terror in the South and
    pulled by demand for factory labour in the North.

    > They did what human beings looking for freedom, throughout history, have
    often done. They left.

    The book stands out both for its broad analysis and for its deeply
    researched detail on the three life stories that carry it along. Ida Mae
    Brandon Gladney left Mississippi in the 30s to work blue-collar jobs in
    Chicago. George Swanson Starling left Florida in the 40s for New York City
    and worked as a porter travelling up and down that same route. Robert Joseph
    Pershing Foster left Louisiana for Los Angeles in the 50s to work as a
    doctor. Ray Charles, a patient, praised him in song.

    These destinations were not random but determined by railway tracks.
    Migrants from Florida and Georgia took the coastal route up to Boston and
    New York. Those from Alabama and Mississippi followed the river up to the
    Midwest cities of Detroit and Chicago. Those from Texas and Louisiana took
    the trains west to Los Angeles and Oakland. Their exodus took them from the
    enforced poverty, brutality and segregation of their old rural lives but
    each of course met prejudice and hostility in their new homes.  
 
13. [_At Home_][bs-home] by Bill Bryson --- Spending all my time at home in
    lockdown I thought it might be interesting to read this history of domestic
    life. I didn't enjoy it as much as his travel books but there are the usual
    interesting facts and stories.

14. [_Brit(ish)_][bs-british] by Afua Hirsch --- ’Where are you from?’ Hirsch
    calls this The Question, asked of her repeatedly with the felt implication
    that what the questioner wants to know is ‘Where are you _really_ from?’
    This gave me pause because it’s a question I often ask people I meet as an
    opening for them to talk. I would say I don’t care what the answer is, it
    might be‘right here’ or more than one place[^1], but directly asking about
    identity is not neutral. I’ve been thinking about something else to ask.

    The book is good on analysis of the intersection of race, class and poverty
    in Britain. It's also good in describing Britain’s post-imperial identity
    crisis. Part of it is in the attempt to be a post-racial society without
    actually coming to terms with the racial society we have been and still are.
    That process is difficult --- as the reaction to the sinking of the slaver
    statue in Bristol has shown --- but necessary. I take visitors to Manchester
    past Lincoln Square and talk about the mill workers who refused to work
    slave-picked cotton but when I'm walking past the grand Victorian buildings
    I don’t think about how much textile industry innovation and wealth had been
    built on that slave labour.
 
15. [_My Name is Why_][bs-sissay] by Lemn Sissay --- the two things I knew about
    Sissay before reading this are that he wrote the poem I often run past on
    the side of [Hardy's Well][hardys] in Rusholme, and that he is the current
    chancellor of the University of Manchester. This memoir covers his childhood
    from when his mother, a young Ethiopian student, was placed in a 'Home for
    Unmarried Mothers' in Wigan. Sissay was taken against her will by social
    services who took away his name and his story, renaming him Norman. It's a
    story of cruel institutions that had a duty to care for him and didn't. 

16. [_Open Borders_][bs-borders] by Bryan Caplan and Zach Weinersmith --- George
    Mason University economist Caplan teams up with [SMBC cartoonist
    Weinersmith][smbc] to make the case for rich countries to allow free
    migration, including untapped trillions in potential wealth as well as clear
    moral imperative. Caplan takes strong opposing arguments and rebuts them
    persuasively. But then I live in a city and already see migration as
    overwhelmingly positive. The arguments focus on economic rather than
    cultural outcomes, which I think people who are less welcoming of migration
    tend to be more concerned about. The illustration lightens up what could be
    dry economic argument and shows how, done as well as this, graphic
    nonfiction can be a brilliant way to present ideas.

17. [_The New Jim Crow_][bs-jim-crow] by Michelle Alexander --- The robustly
    argued case that the racial inequity of the criminal justice system in the
    United States can be thought of as a third era of segregation after slavery
    and Jim Crow laws.

18. [_The Sum of the People_][bs-sum] by Andrew Whitby ★
    --- Counting people might sound like an uncontroversial and mundane
    statistical[^stats] task, but this history of the census since the idea's
    origins in ancient China is absorbing. The Exodus of the Israelites in the
    Old Testament got a whole _Book of Numbers_ for census results. The founding
    fathers of the United States thought a regular census important enough to
    write it into the Constitution, though infamously counted a black slave as
    three-fifths of a free white man. Nazi Germany used census data as a tool
    for genocide. In 1944 a risky daytime Allied air raid on the Kleykamp
    building in The Hague was sent out to destroy the identity records of the
    Dutch population with the aim of protecting some of those the Nazis would
    persecute.

    Who is counted and who isn’t? What questions should be asked? Such decisions
    are contested each time around. The census is a balance of representation in
    democracy for the individual and valuable information for the state.

    > This version of the census --- still used in most countries today --- was
    > a compromise. It acknowledged an unavoidable trade-off between privacy and
    > the state’s need to see in order to function. The traditional census, at
    > its best, has been able to find a delicate balance between these opposed
    > aims. It has succeeded in this because enumeration, by its very nature,
    > requires mass participation, and so the census is owned neither by the
    > state nor by the people but exists as a continuous negotiation between the
    > two.

19. [_Jingo_][bs-jingo] by Terry Pratchett ↻ --- After
    the years I spent buried in Discworld books, I went off to university to
    pick up other interests and affectations like 'serious' literature and
    cardigans. In my 30s I’m returning to my teenage enjoyment of fun books and
    parkas.

    > It was so much easier to blame it on Them. It was bleakly depressing to
    > think that They were Us. If it was Them, then nothing was anyone's fault.
    > If it was Us, what did that make Me? After all, I'm one of Us. I must be.
    > I've certainly never thought of myself as one of Them. _No one_ ever
    > thinks of themselves as one of Them. We're always one of Us. It's Them
    > that do the bad things.

20. [_The Left Hand of Darkness_][bs-left-hand] by Ursula K. Le Guin ★ --- I enjoyed this a lot once I'd gotten into the
    world-building terminology, especially the final trek across the ice sheet
    back to Karhide.

21. [_Caste_][bs-caste] by by Isabel Wilkerson ---  After _The Warmth of Other
    Suns_, I eagerly picked this up the day it was released. Wilkerson
    rigourously frames the subject of racial inequality and injustice in the
    United States in terms of a caste system.

22. [_Hateship, Friendship, Courtship, Loveship, Marriage_][bs-hateship] by
    Alice Munro ★ --- I love how Munro will settle you
    into this familiar place, probably in rural Canada, probably with some
    midlife characters, then unsettle you in just a few pages.

23. [_Around the World in 80 Days_][bs-80-days] by Michael Palin --- Some of
    Palin's TV programmes have been back on the BBC and reminded me how much I
    enjoy his work.

24. [_Now You’re Gonna Believe Us_][bs-robbo] by Andrew Robertson --- I expect
    there will be a lot of books written about Jürgen Klopp's Liverpool FC and I
    expect I will want to read a lot of them.

25. [_New Europe_][bs-new-europe] by Michael Palin --- A tour of Eastern Europe
    in the 00s, in flux between Soviet influence or rule and EU expansion.

26. [_Tequila Oil_][bs-tequila] by Hugh Thomson --- In 1979, aged 18, Thomson
    picks up a used Oldsmobile 98 to drive across the US border down through
    Mexico in a woozy trip working odd jobs, drinking and visiting Mayan sites
    on a quest to sell the car in Belize to pay his way home.

27. [_A Promised Land_][bs-obama] by Barack Obama --- Nothing unexpected but all
    enjoyable to read. Most interesting to me were the insights into how
    multilateral events like the Copenhagen Summit in 2009 actually work and the
    process leading to the Navy SEAL kill-or-capture operation for Osama bin
    Laden. I look forward to the next volume.

28. [_The Moth and the Mountain_][bs-moth] by Ed Caesar ★
    --- An adventure. After the early attempts to conquer Everest by George
    Mallory[^silence] and others, in 1934 Bradfordian WWI veteran Maurice Wilson
    made an eccentric solo attempt to stand first on Earth's highest point by
    flying a second-hand Gipsy Moth plane from London to Tibet and crash landing
    on the slopes of the mountain. He had an imperial bureaucracy set on
    stopping him, no climbing experience beyond a hike up Coniston Old Man and
    only a few hours of flying lessons.

29. [_Terra Incognita_][bs-100-maps] by Ian Goldin and Robert Mugs --- Analysis
    of the major trends and problems we face in human progress and what they
    might mean for us all in the remainder of the century. Well-illustrated with
    '100 maps to survive the next 100 years'.

30. [_In Pursuit of the Traveling Salesman_][bs-tsp] by William J. Cook --- An
    introduction to the [travelling salesman problem][tsp] (TSP). Cook is a
    leading researcher on the TSP and this is an excellent guide through the
    history of the problem and approaches to solving it. The TSP can seem like
    an obscure applied mathematics problem at first glance but, as this book
    makes clear, the understanding gained from the problem and heuristics for
    solving it have been broadly useful in combinatorial optimization and
    theoretical computer science.

[^1]: I don’t have a consistent answer myself.

[^jw]: Jehovah’s Witnesses are in part a print publishing organisation, distributing books, magazines and tracts for evangelism but also to be studied by members.

[^crick]: I had no idea that Francis Crick had been involved in the latter project.

[^stats]: The word _statistics_ originally meaning study of data about the state.

[hardys]: https://en.wikipedia.org/wiki/Hardy%27s_Well

[smbc]: https://www.smbc-comics.com/index.php

[^silence]: As told wonderfully by Wade Davis in _Into the Silence_.

[tsp]: https://en.wikipedia.org/wiki/Travelling_salesman_problem

<!-- Affiliate Links -->

[bs-big-sleep]: https://uk.bookshop.org/a/5340/9781618953292
[bs-i-robot]: https://uk.bookshop.org/a/5340/9781529104639
[bs-secret-barrister]: https://uk.bookshop.org/a/5340/9781509841141
[bs-green-river]: https://uk.bookshop.org/a/5340/9781982120504
[bs-undercover]: https://uk.bookshop.org/a/5340/9781785039126
[bs-two-cities]: https://uk.bookshop.org/a/5340/9788194605836
[bs-snow-leopard]: https://uk.bookshop.org/a/5340/9781610396950
[bs-russian-hist]: https://uk.bookshop.org/a/5340/9780199580989
[bs-sand]: https://uk.bookshop.org/a/5340/9781847394576
[bs-brain]: https://uk.bookshop.org/a/5340/9781781255896
[bs-clay]: https://uk.bookshop.org/a/5340/9780552167574
[bs-warmth]: https://uk.bookshop.org/a/5340/9780141995151
[bs-home]: https://uk.bookshop.org/a/5340/9781784161873
[bs-british]: https://uk.bookshop.org/a/5340/9781784705039
[bs-borders]: https://uk.bookshop.org/a/5340/9781250316967
[bs-sissay]: https://uk.bookshop.org/a/5340/9781786892362
[bs-jim-crow]: https://uk.bookshop.org/a/5340/9780141990675
[bs-sum]: https://uk.bookshop.org/a/5340/9781541619340
[bs-jingo]: https://uk.bookshop.org/a/5340/9780552167598
[bs-left-hand]: https://uk.bookshop.org/a/5340/9781473225947
[bs-caste]: https://uk.bookshop.org/a/5340/9780241486511
[bs-hateship]: https://uk.bookshop.org/a/5340/9780099422747
[bs-80-days]: https://uk.bookshop.org/a/5340/9780753823248
[bs-robbo]: https://uk.bookshop.org/a/5340/9781911613800
[bs-new-europe]: https://uk.bookshop.org/a/5340/9780753823972
[bs-tequila]: https://uk.bookshop.org/a/5340/9780753826942
[bs-obama]: https://uk.bookshop.org/a/5340/9780241491515
[bs-moth]: https://uk.bookshop.org/a/5340/9780241262313
[bs-100-maps]: https://uk.bookshop.org/a/5340/9781529124194
[bs-tsp]: https://uk.bookshop.org/a/5340/9780691163529
