project:
  type: website
  pre-render:
    - "bash scripts/pre-render.sh"
  post-render:
    - "bash scripts/post-render.sh"

website:
  title: "Thomas Ogden"
  search:
    location: sidebar
  navbar:
    search: false
    background: light
  site-url: https://ogden.eu
  page-footer:
    right:
      _'Think deeply of simple things.'_
    border: false

title-block-style: none

format:
  html:
    theme:
      light: [none, tpogden.scss]
      dark: [none, tpogden.scss]
    fontsize: 16px;
    email-obfuscation: references
    html-math-method: katex
    respect-user-color-scheme: true
    include-in-header:
      text: |
        <script data-goatcounter="https://ogden.goatcounter.com/count" async
        src="//gc.zgo.at/count.js"></script>

date-format: YYYY-MM-DD
