---
title: "Book Notes, 2018"
date: "2018-12-31"
categories: [reading]
---

<!-- 
redirect_from:
    - /bookshelf/january-to-march-2018
    - /bookshelf/april-to-june-2018
    - /bookshelf/july-to-september-2018
    - /bookshelf/october-to-december-2018 -->

1. _SPQR_ by Mary Beard --- You can only learn things by
   attaching them to what you've already learned, and I hadn't learned much
   about a thousand years of Roman history. That said, I got more out of it than
   expected because Beard's writing is fun and the book is rarely dry.

   One thing I do know about is the wood tablets at the fort of Vindolanda at
   Hadrian's Wall, because I've been to see them at the museum there.  When the
   first tablets were peeled apart and the ink writing discovered, they were
   rushed to the university at Durham but oxidised before they could be
   transcribed. The message was thought lost but at the medical school they
   found they could still read it in the infrared. And they've been able to
   protect many of the rest dug up so you can see them yourself. The tablets
   include the oldest surviving writing in Latin by a woman, an invitation to a
   birthday party. I recommend a visit.

1. _The Hunt for Red October_ by Tom Clancy --- I always
   picture Jack Ryan as Alec Baldwin.

1. _The Lowland_ by Jhumpa Lahiri ★ --- A sweeping but intimate novel that starts in 
   1960s Calcutta with two young brothers, Subhash and Udayan. Their lives fork, an 
   impulsive Udayan caught up in the Naxalite movement at home and a studious Subhash 
   setting out for university and a life in New England. It's about staying and leaving,
   about parenthood, loss, guilt and responsibility, through four generations of
   a family.

1. _Endurance_ by Alfred Lansing ★ --- Lansing wrote this authoritative account of the Endurance expedition,
   having got hold of most of the diaries kept on the voyage and then
   interviewed the surviving crew. The mission of the great explorer to make the
   first land crossing of the Antarctic went awry when the tallship got stuck in
   the icepack of the Weddell Sea, was crushed and sank leaving the crew without
   a hope.

   There's no way to condense the ordeals and suffering the book details. It is
   unfathomable that they survived. After all that they'd endured over a year,
   Shackleton took a few men in the tiny open boat _James Caird_ and navigated
   800 miles over the most deadly ocean on the planet to hit their only hope of
   rescue, the speck of South Georgia island. Once there, they had to climb over
   the sawtooth mountains and glaciers of the interior to get to the whaling
   station, that itself a route nobody had survived attempting. Shackleton then
   went back to rescue every one of his crew.

   Frank Hurley shot early [colour photographs][hurley] and got the film home.
   They are beautiful.

1. _Ragtime_ by E.L. Doctorow

1. The Carter of La Providence by Georges Simenon (Maigret #4) --- Simenon is great at writing canals, as most other things.

1. _The Innovators_ by Walter Isaacson --- A history of the
   people who invented computers, microprocessors, software and the web, from
   Ada Lovelace to Larry Page. Each character in the story is met only briefly,
   because many people contributed.

   And that's really the theme of the book. We still have this notion of
   looking for lone genius inventors when in fact innovation since the last
   century has driven by brilliant thinkers in collaboration and many
   incremental advances.

1. _Christianity_ by Linda Woodhead --- It's strange when I
   read histories of Christianity having spent my childhood in one branch of it.
   Things I think I know well seen from a different angle. In fact though she
   covers most churches, Woodhead doesn't mention JWs.

   Most interesting in this brief review was to read about the early divide in
   church versus biblical Christianity. Also the role of mystical Christianity
   and the Catholic church's successful absorption of the monastic movement to
   bring it under its own control.

1. _Deep Work_ by Cal Newport ★ --- This book felt important, and I just counted the 
   number of passages I've
   added to my notes from it:  94, which is maybe a record. This is close enough
   to the central thesis:

    > The ability to perform deep work is becoming increasingly rare at exactly
    the same time it is becoming increasingly valuable in our economy. As a
    consequence, the few who cultivate this skill, and then make it the core of
    their working life, will thrive.

   And this from a section on life satisfaction:

    > Most people assumed (and still do) that relaxation makes them happy. We
    want to work less and spend more time in the hammock. But the results from
    Csikszentmihalyi’s ESM studies reveal that most people have this wrong. The
    best moments usually occur when a person’s body or mind is stretched to its
    limits in a voluntary effort to accomplish something difficult and
    worthwhile.

1. _The Yellow Dog (Maigret #6)_ by Georges Simenon --- A
   typical Maigret setting of a murder and a conspiratorial group of men in a
   small French town, this time Concarneau. Maigret sorts it all out with a few
   frothy beers of course.

1. _Cities of the Plain_ by Cormac McCarthy --- The last in
   the Border Trilogy brings John Grady Cole and Billy Parham together soon
   after the Second World War, in work on a ranch. The Old Testament Cities of
   the Plain were Sodom and Gomorrah, so we know the old world is in fire and
   brimstone. They make the crossing of the Rio Grande once more to find the
   last of it. As always McCarthy writes horses better than women.

   > The man smiled at him a sly smile. As if they knew a secret between them,
   these two. Something of age and youth and their claims and the justice of
   those claims. And of their claims upon them. The world past, the world to
   come. Their common transciencies. Above all a knowing deep in the bone that
   beauty and loss are one.

   Also this, from [the New York Times review][nytcm]:

   > That brief moment between a culture's existence and extinction -- this is
   the border that McCarthy's characters keep crossing and recrossing, and the
   one story, as he's forever writing, that contains all others. Throughout the
   trilogy, we keep encountering witnesses -- former revolutionaries, priests,
   gypsies -- in whose testimony alone human history survives. As in Proust, the
   storytellers are inseparable from their tales.


1. _The Spanish Civil War_ by Helen Graham --- I'm putting
   together a reading pile on the Spanish Civil War, and I like these short
   intros for a place to start. I'd never considered that there's no Civil War
   museum, though maybe in Barcelona soon. Francoists "always referred to the
   war as a 'crusade' or 'fight for national liberation'". A reminder how
   quickly people can turn to killing their own neighbours, even relatives, when
   scared and told these people are the danger. Britain's non-intervention.

   > The military coup unleashed what was in effect a series of culture wars:
   urban culture and cosmopolitan lifestyles versus rural tradition, secular
   against religious; authoritarianism against liberal political cultures;
   centre versus periphery; traditional gender roles versus the 'new woman';
   even youth against age, since generational conflicts were also present.

   New culture war, same as the old culture war.

1. _Men Without Women_ by Ernest Hemingway --- This second
   set of stories was published in 1927. It's the one with _Hills Like White
   Elephants_ and _The Killers_. The stories flow through the gaps, and you know
   he's reporting life where he's seen it, whether bullfighting in _The
   Undefeated_, boxing in _Fifty Grand_ or war on the Italian Front in _Now I
   Lay Me_ and _In Another Country_.

   In [an interview, later][nyeh]:

   > I can remember feeling so awful about the first war that I couldn’t write
   about it for ten years,” he said, suddenly very angry. “The wound combat
   makes in you, as a writer, is a very slow-healing one. I wrote three stories
   about it in the old days—‘In Another Country,’ ‘A Way You’ll Never Be,’ and
   ‘Now I Lay Me.’

1. _The Goldfinch_ by Donna Tartt ★  --- This and _The Secret History_ are two of the most enjoyable novels I can
   remember reading in a long time. Recommended by everyone, and now by me.

   > Caring too much for objects can destroy you. Only–if you care for a thing
   enough, it takes on a life of its own, doesn’t it? And isn’t the whole point
   of things—beautiful things—that they connect you to some larger beauty?

1.  _Wind, Sand and Stars_ by Antoine de Saint-Exupéry --- _Saint-Ex_ wrote this memoir of his daring adventures as an early aviator
    for the French Aéropostale, expanding into his thoughts on friendship, death
    and living a meaningful life. He was a pioneer of the mail routes over the
    Sahara and the Andes. In undependable aircraft, over mountain terrain with
    navigation by landmarks on the ground or the stars at night, this was a
    perilous occupation.

    > Nothing, in truth, can ever replace a lost companion. Old comrades cannot
    be manufactured. There is nothing that can equal the treasure of so many
    shared memories, so many bad times endured together, so many quarrels,
    reconciliations, heartfelt impulses. Friendships like that cannot be
    reconstructed. If you plant an oak, you will hope in vain to sit soon under
    its shade. For such is life. We grow rich as we plant through the early
    years, but then come the years when time undoes our work and cuts down our
    trees. One by one our comrades deprive us of their shade, and within our
    mourning we always feel now the secret grief of growing old.

1. _Open_ by Andre Agassi --- The interesting thing about
   Agassi's story is he hated his sport. Emmanuel Agassi, an Iranian Olympic
   boxer migrated to Las Vegas, decided his son would be a tennis pro before he
   was born. Rigged up a machine to fire balls at a toddler thousands of times a
   day and sent him on to academies. In Andre's telling, by the time he got to
   decide what he wanted to do he only had one option, one he didn't want. Even
   when that job got him rich, famous and married to Brooke Shields.

   Only when things fell apart, he got a ban for crystal meth and dropped to the
   bottom did Agassi get to enjoy tennis. The rise from there back to world
   number one late in his career is the real sporting life.

2. _Running with the Kenyans_ by Adharanand Finn --- Finn
   moves for six months to the marathon capital of the world, a town in Kenya
   called Iten. He hopes to find out what makes the locals worldbeaters at
   distance running. Running miles to school every day? Running barefoot? Ugali?
   Altitude? Attitude? And of course it's a bit of all of that. Except the
   barefoot running, Kenyans wear trainers.

3. _Hidden City_ by Karl Whitney --- I got this book about
   Dublin from Daunt before visiting in August, but it's more a book for locals
   seeking out obscure bits of their city. Whitney explores underground rivers,
   ghost towns hit by the financial crash, sewage systems and bus networks.
   Luckily I can happily read about infrastructure all day, I don't know why.

4. _The Green Road_ by Anne Enright --- Picked up from the
   great Irish fiction section of Chapters in Dublin. We have a family on the
   west coast of Ireland, Rosaleen and her children.

   > He did not seem happy, he seemed a bit impatient but, _That is because I am
   well_, Constance thought, I have been wasting his time with my robust good
   health, I have been wasting everyone's time! Her clever body had been doing a
   great job. Complex. Microscopic. Quiet. The map of light that was her left
   breast was not frightful but beautiful, and the marbled black and white of
   its sonic depths was lovely too.

   Constance stays and the others go off to New York and Mali. We hear the
   separate stories of them, and then they're brought back together.

   > She had not thought it would be dark, not yet, the way the Atlantic sky
   held the light for so long after the sun was down, something to do with the
   height of the heavens out here on the green road. The west was still open and
   clear, but the ground under her feet was tricky enough. All the colour was
   going from things and nothing was easy to see. You could not tell grey from
   grey.

5. _A Crime in Holland_ by Georges Simenon

6. _The Grand Banks Café_ by Georges Simenon

1. _The Undercover Economist Strikes Back_ by Tim Harford --- The sequel to his tour of microeconomics, this one covers macro, with a
   bit of the life of Bill Phillips and his [MONIAC][moniac] hydraulic computer.

   We learn about failures of supply like the 'prison-camp recession' and
   failures of demand like the ['babysitting co-op recession'][br], and that in
   practice it's hard to tell which is happening. So in response, short-run
   Keynes, long-run classical is a rule of thumb. It then covers inflation,
   printing money, GDP, and there's a chapter explaining how independent central
   banks committed to low inflation work as _Dr Strangelove_-like doomsday
   devices. Having them should mean we don't have to use them, but it was the
   ECB's device that went off in Greece.

2. _A History of the World_ by Andrew Marr --- I don't know
   why after _SPQR_ I've gone for another history book covering such a mad
   amount of time but I liked the style of Marr's _History of Modern Britain_ so
   thought I'd like this one too. The time spent on non-European histories was
   most useful for me, particularly what was going on in China relative to what
   was happening with Christianity and Islam in Europe and the Middle East. Also
   the Americas and Russia. I should read some Tolstoy.

   Marr makes no apology for it being a history of significant individuals but
   doesn't always convince me that someone else would not have come along with
   the same idea. Watt and his steam engine for one example, or Ghandi's Salt
   March. In some cases it is clear that one person moved the world in a certain
   direction, like Zimmermann with his [Telegram][tele] and most significantly
   Genghis Khan.

3. _The Vital Question_ by Nick Lane ★ --- Lane takes us through a radical, wide-ranging new theory on the
   origins of life and then complex life. The theory puts energy right at the
   centre of the problem with the sort of derivation from first principles you
   get in physics. So I enjoyed that.

   > The energy we gain from burning food in respiration is used to pump protons
   across a membrane, forming a reservoir on one side of the membrane. The flow
   of protons back from this reservoir can be used to power work in the same way
   as a turbine in a hydroelectric dam.

   It starts with a search for the sort of consistent energy gradients needed to
   kick things off. He rules out lightning (not enough) and UV radiation (too
   destructive) but reveals one candidate on Earth with the right conditions:
   those hydrothermal vents in the deep ocean.

   > Exactly the kind of dissipative structures that we seek: continuous flow,
   far-from-equilibrium electrochemical reactors.

   Once simple life is sorted we find out how, after two billion years with
   nothing but bacteria and archea, eukaryotes (complex life like animals and
   plants) branched off with one extremely rare event when a bacterium got
   inside an archea (the rare thing is that they didn't both immediately die)
   and formed a nucleus with a mitochondria power plant. Why that was so
   revolutionary: single-cell organisms have a limit on how big they can get
   while bringing in enough energy to support themselves, because the energy
   throughput of the membrane is limited by surface area, which increases
   squared as the volume increases cubed.

   The rest of the book takes the idea on to why complex life is like it is:
   sex, ageing, disease, death. There's a lot of biology terms through the book,
   which left me needing the glossary or lost in an argument. He's good at
   recapping though so I stopped being bothered about that, just skipping on to
   catch up.


4. _The Marches_ by Rory Stewart --- A journal of long walks
   in the borderlands between England and Scotland. The first, along Hadrian's
   Wall, he takes with his 89-year-old father, comparing the end of Roman Empire
   with retreat of British Empire, which in the Malayan Civil Service and MI6
   his father saw firsthand. The second is a meandering walk from Cumbria to
   Crieffe, investigating what it means to live in the middleland, and how firm
   the boundaries really are.

   > While the people hereabouts (and a good way north) have over the past 2,000
   > years spoken Cumbrian, Welsh, Latin, Northumbrian, Norman French and
   > Borders English, they have never spoken Scottish Gaelic and never called
   > this place Alba.

5. _Grave New World_ by Stephen D. King ---  A look at the
   retreat of globalisation and return of nationalists over the last couple of
   years, and where this could take us.


6. _Killers of the Flower Moon_ by David Grann ★ {%
   include dash.html %} This is a shocking, tragic crime history from 1920s
   Oklahoma. The sisters in a family of the Osage tribe of Native Americans,
   rich from oil strikes on the rocky land they'd been shoved onto, started
   dying off. The surviving family have to pay for the new federal Bureau of
   Investigation to pull together a band to find the murderers and the
   conspiracy protecting them.


[nytcm]: http://www.nytimes.com/books/98/05/17/reviews/980517.17moslet.html
[nyeh]: http://www.newyorker.com/magazine/1950/05/13/how-do-you-like-it-now-gentlemen

[tele]: https://en.wikipedia.org/wiki/Zimmermann_Telegram
[moniac]: https://en.wikipedia.org/wiki/MONIAC
[br]: https://en.wikipedia.org/wiki/Capitol_Hill_Babysitting_Co-op

[hurley]: https://www.flickr.com/photos/statelibraryofnsw/albums/72157618020442474
