---
title: "The Oldest Referee"
date: "2013-01-20"
categories: [personal]
---

The Manchester Accountants League plays Sunday football at Hough End Playing
Fields, a vast grid of twenty or so muddy, bumpy pitches in a park in
Withington. A few years ago I played for a newly-formed pub team based at the
Rising Sun, just off Deansgate. Other teams in the league included Maccabi, a
Jewish team, Mesopotamians, all players from Iraq, and, a division above us,
Village Manchester, relatively famous for their [success in IGLFA World
Championships][1]. The 'accountants' bit of the name is an anachronism.
The football, at least when I played, was more agricultural than actuarial.

One of the referees of the league's matches was remarkably advanced in years ---
we didn't know how old but guessed he could've been eighty. He was good-humoured
but dead serious about his work, tall and spindly. He hardly moved on the pitch,
staying in the centre circle to watch the game from there and only mobilising
for important events like corners.

I never understood why anyone would want to get up on Sunday mornings to take
verbal abuse from twenty-two angry, hungover Mancunians who think they're better
at football than they are. Me included. The pay was a token £25 for two hours
work and travel. Some people obviously love the game enough though, including
this old feller still standing out in the rain and wind when he could reasonably
have been at home doing crosswords.

We thought he was funny, and respect for his age meant he didn't seem to get as
much abuse as the other officials. This despite the fact that he seemed to have
quite unique ideas on how the game should be adjudicated. I remember one game of
ours he was doing when two players went into a tackle and the ball went out off
their man for a throw-in. Both players claimed it, he gave it to the opposition
and our player made a comment he didn't like. As punishment, to everyone's
bemusement, he upgraded the award to a direct freekick on the edge of our area.
I was near him and said 'Listen, you can't just turn throw-ins into freekicks.
That's not a rule.' He replied 'There are no rules in football, just laws, and
I'm the judge and executioner.' Well, what do you say to that.

I only played for that team for one season as I got fed up of having my knees
hacked at by lumbering defenders who preferred that approach over chasing after
me. A few months after I'd stopped playing, I turned on the sports news one
morning to see the old guy there on the screen. Mr Thomas 'Tommy' Clarke was,
they said, the oldest FA referee in the country, at 86. In the entire league
pyramid, from Manchester Accountants Division Two to the Premier League, the
oldest.

Another funny decision Tommy Clarke made went our way. After the other team took
a corner the ball broke and a teammate of mine, Chris, set off on a
counterattack, dribbling into their half. I caught up alongside him and just as
he went to slide the ball to me, a defender took him down from behind. It was a
hilariously filthy foul. He was, I considered, the last defender and should've
been sent off. The referee blew a distant whistle and, when he finally made it
up to our end of the pitch, pointed to the penalty spot. Their defenders were
outraged. The thing was, the foul wasn't in the penalty area. Chris's forward
momentum hadn't even carried him into the D, as was obvious from the long furrow
he'd made through the mud after being felled. It stopped about 25 yards from
goal. After wailing at the ref, the defenders turned on us, telling us to own
up: that it was outside the box and we knew it. We were laughing too hard
even if we wanted to tell him, which we didn't. We told them where to go. We
hadn't won a game in the league yet, we were having that. The penalty levelled
the match.

I looked up the oldest referee to see if he was still out on Hough End on Sunday
mornings. Turns out not. He retired the following season, blowing his last
whistle at the age of 87, and died a couple of years later in 2009. His death
was [reported in the Manchester Evening News][2], who claimed that Mr Clarke was
in fact the oldest referee in the world. I don't know how you'd check that. But
either way he'd apparently been refereeing games since 1948, which is amazing.
It even quoted the exact words he said to me after that freekick decision,
wisdom he apparently gave out often.

Thinking again about the penalty, perhaps Tommy Clarke knew exactly what he was
doing. Maybe he'd seen the whole thing and just pretended to have been too far
away. It says in that report that he'd only brandished four red cards in his
whole career. Maybe he didn't want to send the lad off but decided a penalty
was sufficient punishment for a goal-preventing foul. Not in the rules, but a
reasonably fair outcome if you think about it. 'There are no rules
in football, just laws, and I'm the judge…'

An honour to have been refereed by you, Mr Clarke. It was definitely our throw.

[1]: http://www.vmfc.co.uk/
[2]: http://www.manchestereveningnews.co.uk/news/greater-manchester-news/worlds-oldest-ref-dies-915519
[3]: http://www.youtube.com/watch?v=uqpJ6XYykHE
