---
title: "Book Notes, 2014"
date: "2014-12-31"
categories: [reading]
---

1. _Old School_ by Tobias Wolff ★ --- In [an interview][pr] soon after finishing _Old School_, Wolff suggests
   Robert Frost — who appears in the novel — 'didn’t fully understand his own
   poem', or pretended not to. The theme of a writer's intention comes up both
   in Frost's reading of George's story as a dig at him and Susan's reading of
   the narrator's work as a trick on Hemingway, both unintended. Authentic or
   fake? Fiction or memoir? The writer is morally required to set down the
   truth, but cannot.

   > A more truthful dust-jacket sketch would say that the author, after much
   floundering, went to college and worked like the drones hed once despised,
   kept reasonable hours, learned to be alone in a room, learned to throw stuff
   out, learned to keep gnawing at the same bone until it cracked.

2. _Runaway_ by Alice Munro

3. _Hitch-22_ by Christopher Hitchens

4. _The White Tiger_ by Aravind Adiga

5. _Stoner_ by John Williams

6. _You Shall Know Our Velocity_ by Dave Eggers

7. _Joyland_ by Stephen King

8. _Adventures of Hergé_ by Jose-Louis Bocquet et al.

9. _Sustainable Energy Without the Hot Air_ by David J. C. MacKay ★

10. _Breakfast of Champions_ by Kurt Vonnegut ★

11. _The Sun Also Rises_ by Ernest Hemingway

12. _I Am Zlatan_ by Zlatan Ibrahimović

13. _Advanced Marathoning_ by Peter Pfitzinger, Scott Douglas

14. _Revolutionaries_ by Jack Ravoke

15. _Swimming Home_ by Deborah Levy

16. _The Lighthouse_ by Alison Moore

17. _Flash Boys_ by Michael Lewis

18. _Feynman_ by Jim Ottaviani, Leland Myrick

19. _The Sum of All Fears_ by Tom Clancy
