---
title: "Pickup Sticks and Pi"
date: "2011-03-14"
categories: [research]
page-layout: article
---

At school we learn that 3.1415927... is the ratio of a circle's circumference to 
its diameter but $\pi$ turns up all over the place in mathematics. For example, did 
you know you can measure $\pi$ just by dropping sticks on a table and counting them? 
This is because $\pi$ has a role in statistics too. Try it for yourself, and below 
we'll visit the story of how this remarkable trick was discovered.

_Click on the board to drop sticks._ Each time you click, <span id="num-sticks">100</span> 
will be dropped and the number that cross a line will be counted. I dropped 10 to 
start you off.

<canvas id="pickup-canvas" width="480" height="640"></canvas>

::: {.column-margin}
<form id="sticks-form">
    <label>Number of sticks to drop:</label>
    <select id="num-sticks-select" size="1">
        <option value="10">10</option>
        <option value="100" selected="selected">100</option>
        <option value="1000">1,000</option>
        <option value="10000">10,000</option>
    </select>
</form><br />

_Click on the board!_ Each time you click, <span id="num-sticks">100</span> sticks 
will be dropped and the number that cross a line will be counted. I dropped 10 to start
you off.
:::

<script src="assets/pickup.js"></script><br />

| Sticks Dropped                  | Crossed a Line                  | Estimate of $\pi$            | Error                              |                 
| ------------------------------: | ------------------------------: | ---------------------------: | ---------------------------------: | 
| <span id="stick-count">0</span> | <span id="cross-count">0</span> | <span id="estimate">0</span> | <span id="error-percent">0</span>% |

<script>
    initGame(
        document.getElementById('pickup-canvas'),
        document.getElementById('stick-count'),
        document.getElementById('cross-count'),
        document.getElementById('estimate'),
        document.getElementById('error-percent'),
        document.getElementById('num-sticks-select'),
        document.getElementById('num-sticks')
    );
</script>

Does the estimate get better as you drop more sticks (i.e. does the error get smaller)? 
How close to $\pi$ can you get after 100,000 sticks or 1,000,000?

## Buffon's Needle

In 1777, a French philosopher called Georges-Louis Leclerc, Comte de Buffon, wrote out 
an elegant theorem that turned out to be the earliest problem in geometric probability.

Buffon discovered that if you draw a set of equally-spaced parallel lines (say, $d$ 
centimetres apart) and drop sticks on them that are shorter than the spacing (say $l$ 
centimetres long, where $l$ is less than $d$) then the probability of a stick crossing 
a line is 

$$\frac{2 l}{\pi d}.$$

This means that if you drop lots of sticks randomly and count how many cross
the parallel lines, you can calculate what $\pi$ is by rearranging the
formula to get

$$ \pi = \frac{2ls}{c d} $$

where $s$ is the number of sticks you drop and $c$ is the number that
crossed a line.

Isn't that remarkable? Buffon had worked out that you can calculate $\pi$ just by
dropping a bunch of sticks on a table --- no circles required! The problem is known as
Buffon's Needle.

As usual in statistics, we want to take a big sample to get an estimate close to the
true probability. If I ask 5 people 'are you left handed?' and you ask 500 people the
same, we know that your bigger sample is likely to give us the better idea of what
proportion of people are left handed in the whole country. The same applies here --- to
get a good sample we need to drop a lot of sticks.

Perhaps that's why it took a long time after Buffon's discovery for somebody to actually
try it themselves, but in 1901 the Italian mathematician Mario Lazzarini gave it a go.
He span around and dropped over 3,400 sticks onto the floor, counted up the number that
crossed over lines and estimated $\pi$ to be 3.1415929. We know $\pi$ to be
3.1415927..., so he was correct in the first 6 digits, an error of 0.000006%. That's
good! Suspiciously good in fact, and so improbable that it's more likely he cheated.
Hoist by his own probabilistic petard?

## Monte Carlo

What Lazzarini did we would today call a simulation. Simulations have become vastly
easier and more important now that we can use computers to do the legwork for us. I'm
sure a dizzy Lazzarini would've appreciated one. Simulations like this, where we use
randomness to give us a sample of results, are called Monte Carlo methods, after the 
European city famous for its casino.

Monte Carlo methods are useful in physics as we can model a large system with a
huge number of possible states with a much smaller, but representative subset. It has
important uses in thermal physics, molecular modelling, astrophysics and weather
forecasting. And, as Buffon showed 200 years ago, can even be used to calculate $\pi$.

Buffon may have been the earliest human to discover this result but the natural world 
might have got there first. A paper in _Behavioral Ecology_ suggests that [ants use 
Buffon's Needle][mugford] to determine, before initiating an emigration, if a nest has 
sufficient area to house their colony.[^1]

## References

- Jos Thijssen, _Computational Physics_. Cambridge University Press, second edition, 
    March 2007.

- Daniel V. Schroeder, _An Introduction to Thermal Physics_. Addison Wesley, first 
    edition, August 1999.

- J. J. O&rsquo;Connor and E. F. Robertson. [_Georges Louis Leclerc, Comte de 
    Buffon_][connor].

- Eric W. Weisstein, [_Buffon's Needle Problem_][mathworld], MathWorld.

- S. T. Mugford, E. B. Mallon, and N. R. Franks, [_The accuracy of Buffon’s needle: a 
    rule of thumb used by ants to estimate area._][mugford] Behavioral Ecology, Vol. 12 
    No. 6.

[connor]: http://www-history.mcs.st-andrews.ac.uk/Biographies/Buffon.html
[mugford]: https://academic.oup.com/beheco/article/12/6/655/462588
[mathworld]: http://mathworld.wolfram.com/BuffonsNeedleProblem.html
[cobb]: https://research.manchester.ac.uk/en/persons/cobb

[^1]: Thanks to [Matthew Cobb][cobb] for the pointer.